### ISSUE TITLE
`Merkle proofs automatic validation` feature

### ISSUE THREAD

**Issue by Sina-KH** [xssnick/tonutils-go#113]
Hi!

In `readme` file, `Merkle proofs automatic validation` is not checked.
But I see `Merkle proofs` are checked in the features.
How can I make sure that Merkle proofs work on my integration?

Beat Regards.

**Comment by xssnick** [comment]
Hi, 
Currently Merkle proofs are available for manual usage only (see https://github.com/xssnick/tonutils-go/blob/master/adnl/storage/client.go#L269 for example), you can check and create them.

Proofs for lite server methods responses are not validated yet, so in production I recommend to use your own ton node, then it will be safe.

**Comment by xssnick** [comment]
I have a plans to add optional (with ability to enable) validation feature, but don't have exact timings for it. Correct liteserver proofs validation requires to synchronize key blocks, so it will require to download them on initialization and also will cost some performance. 

So if you are doing something on the server side, in my opinion it is still better to use your own node without proofs.

**Comment by Sina-KH** [comment]
Thanks.
Please let me explain my situation and I hope you can help me :)

I'm working on `iOS Application` for `TonCoin Wallet Contest`. I was using the latest version of [tonlib mono repo](https://github.com/ton-blockchain/ton) until now, But, It seems It does not support wallet version 4, and dns resolving features, for example.

So, Today, I've tried to implement your sdk into my iOS application, using cgo, but I'm not sure about:

1. Do you think your sdk support features I need? For example Merkle proofs and estimating transfer fees.

2. Do you know about `tonlib mono repo` details? Can I somehow add wallet versioning and other new features into this legacy library? My app is almost complete on this library but missing `wallet version support`, `dns support` and `ton connect v2`

Any help highly appreciated. Thanks 🌹

**Comment by xssnick** [comment]
1. DNS and wallets are supported, but fees estimation and merkle proofs for LS methods are not yet. Currently tonutils is more suitable for server side usage, you could check https://github.com/andreypfau/ton-kotlin, maybe it will fit better for your task.
2. I Haven't used tonlib, but if you know c++, I think it is possible to add wallet v4 support, it should be simillar to v3.

**Comment by Sina-KH** [comment]
Thanks for your help, I'll consider your suggestions. 👍 
btw Your library and it's simplicity is very awesome. Great work. 💯 
You can close this issue if you want. :)
