### ISSUE TITLE
Transactions in a block in the past

### ISSUE THREAD

**Issue by hlee4real** [xssnick/tonutils-go#122]
Hey Nick, I'm new to Ton Blockchain. Can I ask have you implemented a method to get all transactions of an exact block yet? With go-ethereum it looks like : block, err := client.BlockByNumber(context.Background(), big.NewInt(3000000)).
Hope I will get your answer soon :) thank you very much for this library.

**Comment by xssnick** [comment]
Hi, you could use `GetBlockTransactionsV2` method. Usage example can be found in [block-scan](https://github.com/xssnick/tonutils-go/blob/master/example/block-scan/main.go#L117).

**Comment by xssnick** [comment]
In TON, there could be many parallel blocks in the same time because of sharding. In block-scan example we taking latest masterchain block (and each next when available), then getting basechain shard blocks related to master block and getting transactions for each shard block.

**Comment by hlee4real** [comment]
Hi, I've tried and follow your block-scan. It works for new blocks and new shards. but what exact i'm trying to find is scan transactions in the past of a block. you can follow this url for example:
https://tonwhales.com/explorer/block/30283112

**Comment by xssnick** [comment]
Prepared example for you, it is doing what you need:
```golang
func main() {
	client := liteclient.NewConnectionPool()

	// connect to mainnet lite servers
	err := client.AddConnectionsFromConfigUrl(context.Background(), "https://ton-blockchain.github.io/global.config.json")
	if err != nil {
		log.Fatalln("connection err: ", err.Error())
		return
	}

	// initialize ton api lite connection wrapper
	api := ton.NewAPIClient(client)

	// find master block
	master, err := api.LookupBlock(context.Background(), -1, -0x8000000000000000, 30283112)
	if err != nil {
		log.Fatalln("get masterchain info err: ", err.Error())
		return
	}

	// find it's shard blocks
	currentShards, err := api.GetBlockShardsInfo(context.Background(), master)
	if err != nil {
		log.Fatalln("get shards err:", err.Error())
		return
	}

	// we also want to see master block transactions
	currentShards = append(currentShards, master)

	for _, shard := range currentShards {
		var fetchedIDs []ton.TransactionShortInfo
		var after *ton.TransactionID3
		var more = true

		// load all transactions in batches with 100 transactions in each while exists
		for more {
			fetchedIDs, more, err = api.GetBlockTransactionsV2(context.Background(), shard, 100, after)
			if err != nil {
				log.Fatalln("get tx ids err:", err.Error())
				return
			}

			if more {
				// set load offset for next query (pagination)
				after = fetchedIDs[len(fetchedIDs)-1].ID3()
			}

			for _, id := range fetchedIDs {
				// get full transaction by id
				tx, err := api.GetTransaction(context.Background(), shard, address.NewAddress(0, byte(shard.Workchain), id.Account), id.LT)
				if err != nil {
					log.Fatalln("get tx data err:", err.Error())
					return
				}
				log.Println(tx.String())
			}
		}
	}
}

```

**Comment by hlee4real** [comment]
Thank you so much for answering my question so quickly. but let me ask about shard and workchain when calling LookupBlock function. Is that the default set value and will it always be? workchain=-1 and shard=. -0x8000000000000000

**Comment by xssnick** [comment]
For master chain yes, it is constants

**Comment by hlee4real** [comment]
great. so that I just need to change seqno to scan another blocks from your example right?
