### ISSUE TITLE
always get "Transfer err:failed to get account state: adnl request timeout, node 185.86.79.9:4701",why this happen?

### ISSUE THREAD

**Issue by selfmakeit** [xssnick/tonutils-go#127]
here is my code
```
var messages []*wallet.Message
messages = append(messages, &wallet.Message{
    Mode: 1,
    InternalMessage: &tlb.InternalMessage{
    Bounce:  false,
    DstAddr: addr,
    Amount:  amount,
    Body:    comment,
  },
})
// send tx and wait for it
tx, block, err := w.SendManyWaitTransaction(context.Background(), messages)
if err != nil {
	global.LOG.Sugar().Error("Transfer err:", err.Error())
	return err
}
```

**Comment by xssnick** [comment]
Hi, looks like liteserver you are using is down, try to use diff one, or initialize pool using config url, like in example

**Comment by selfmakeit** [comment]
> Hi, looks like liteserver you are using is down, try to use diff one, or initialize pool using config url, like in example

hey, thanks for reply,but problem still exists :
```
client := liteclient.NewConnectionPool()
	configUrl := "https://ton-blockchain.github.io/global.config.json"
	err = client.AddConnectionsFromConfigUrl(context.Background(), configUrl)
	if err != nil {
		global.LOG.Sugar().Error("add connections err:", err.Error())
		return "",err
	}
```

**Comment by xssnick** [comment]
> > Hi, looks like liteserver you are using is down, try to use diff one, or initialize pool using config url, like in example
> 
> hey, thanks for reply,but problem still exists :
> 
> ```
> client := liteclient.NewConnectionPool()
> 	configUrl := "https://ton-blockchain.github.io/global.config.json"
> 	err = client.AddConnectionsFromConfigUrl(context.Background(), configUrl)
> 	if err != nil {
> 		global.LOG.Sugar().Error("add connections err:", err.Error())
> 		return "",err
> 	}
> ```

Try to change config url to https://ton.org/global.config.json, maybe yours is outdated and some nodes from it are down. Also to skip bad nodes you may add retry and context timeout
