### ISSUE TITLE
Support wallet V3R1

### ISSUE THREAD

**Issue by akme** [xssnick/tonutils-go#128]
Hey there,
is it possible to add support for V3R1 wallets? now only V3R2 implemented 

https://github.com/xssnick/tonutils-go/blob/d9f8c2c9ac26bd1407cbf72f813751749a3848a3/ton/wallet/address.go#L57-L76

**Comment by xssnick** [comment]
Hi, yes, will add in v1.8

**Comment by akme** [comment]
Thank you! That would be aweseome!

**Comment by akme** [comment]
Hey there! Any ETA? We are migrating operations to your lib, but support for V3R1 is a blocker :(

**Comment by xssnick** [comment]
If it is urgent for you, I will push it to dev branch tomorrow, and you can link it to your project

**Comment by akme** [comment]
That would be super helpful!

**Comment by xssnick** [comment]
Done, you could do `go get -u github.com/xssnick/tonutils-go@41e9d42875c90edfb07b404dc5c42acd78060127` and use dev version. V3R1 is supported as wallet version for initialization.

**Comment by akme** [comment]
Amazing, thank you! Looking forward for 1.8 release :)

**Comment by xssnick** [comment]
v1.8 released
