### ISSUE TITLE
Send jetton with comment

### ISSUE THREAD

**Issue by newset** [xssnick/tonutils-go#130]
how to add messge in jetton tansfer？

**Comment by xssnick** [comment]
Hey, i've [updated jetton-transfer example](https://github.com/xssnick/tonutils-go/blob/master/example/jetton-transfer/main.go#L55), now it also shows how to add comment.

**Comment by newset** [comment]
> Hey, i've [updated jetton-transfer example](https://github.com/xssnick/tonutils-go/blob/master/example/jetton-transfer/main.go#L55), now it also shows how to add comment.

tried with v1.8.0, the transfer did succeed though, comment is still missing.

https://testnet.tonscan.org/address/EQDMHHszAZx0eeQLCR9yXuXf_LuqB_44qemM3pZLUWUvWKC0#transactions

https://testnet.tonscan.org/address/EQCWaXAdYlJcPayZdeXOuQZ24u0-FJnSTaWMj8dTXrD5tTcc#transactions

**Comment by xssnick** [comment]
Hm, maybe tonscan not shows jetton comments, I tried to send and see comment in tonkeeper

![IMG_A6A9A706BD70-1](https://github.com/xssnick/tonutils-go/assets/9332353/7124e8ea-6b11-438d-871f-8435ee2202dc)

**Comment by newset** [comment]
> Hm, maybe tonscan not shows jetton comments, I tried to send and see comment in tonkeeper
> 
> ![IMG_A6A9A706BD70-1](https://user-images.githubusercontent.com/9332353/261222781-7124e8ea-6b11-438d-871f-8435ee2202dc.jpeg)

you are right, tonscan skipped jetton transfer message.
