### ISSUE TITLE
Optimize raptorq/discmath package and cover with tests

### ISSUE THREAD

**Issue by xssnick** [xssnick/tonutils-go#137]
RaptorQ package (used for forward error correction encoding) is used by RLDP protocol, which is one of the building blocks of TON communication, it is used by such components as Storage, Proxy, Nodes. Current implementation is not so efficient as it could be, for example maps usage can be replaced to arrays/slices.
 
The task is to optimize [raptorq](https://github.com/xssnick/tonutils-go/tree/master/adnl/rldp/raptorq)+[discmath](https://github.com/xssnick/tonutils-go/tree/master/adnl/rldp/raptorq/discmath) packages, cover them with unit tests and add benchmarks. Please don't use CGO or external libraries.

You could start from benchmarks to understand current behaviour and speed. Usage example can be found in [rldp](https://github.com/xssnick/tonutils-go/tree/master/adnl/rldp) package.

If you want to take the task, leave a comment here (time estimation will be a plus). When you are done, just make PR to `dev-v19` branch, and leave a comment here.

**Comment by jokly** [comment]
Hello! I want to take on optimization [SparseMatrixGF2](https://github.com/xssnick/tonutils-go/blob/master/adnl/rldp/raptorq/discmath/sparse-matrix.go)
Do you have article about how sparse matrix gf2 works?

**Comment by xssnick** [comment]
> Hello! I want to take on optimization [SparseMatrixGF2](https://github.com/xssnick/tonutils-go/blob/master/adnl/rldp/raptorq/discmath/sparse-matrix.go) Do you have article about how sparse matrix gf2 works?

Hi, cool! Sparse matrix is a matrix that stores only existing values, but not storing empty slots ([wiki details](https://en.wikipedia.org/wiki/Sparse_matrix)). GF2 means that it can have just 2 values (true/false). 

But in our case we may sacrifice sparsity, and just store some kind of bit mask. Try to measure actual dimensions that it usually keeps, and if it is not so huge we can use just a byte slice as a bit mask with a full dimension.
