### ISSUE TITLE
wallet.SendWaitTransaction deploys the contract instead of sending the transaction

### ISSUE THREAD

**Issue by SsNiPeR1** [xssnick/tonutils-go#143]
When I try to send a transaction using wallet.SendWaitTransaction, the contract gets deployed. When I do it second time, it tries to re-deploy the contract, which results in "Something happened but we don't understand what.", but no coins get actually sent for some reason.

You can see it here: https://testnet.tonviewer.com/kQDdo8y5BSM2tsDB29FxRsQ1TC5-523KZ5xgbpPjdDwHIhgE

**Comment by xssnick** [comment]
Hi, it looks like not enough coins on balance to send, and mode 3 is used (default). Try to increase balance on the wallet before sending, or use mode 130 (128+2) to send all remaining balance.
