### ISSUE TITLE
Fix policy ProofCheckPolicyFast with multiple existing shards

### ISSUE THREAD

**Issue by KudinovKV** [xssnick/tonutils-go#155]
Hey! Could you please check, current [example](https://github.com/xssnick/tonutils-go/blob/master/example/account-state/main.go) is not work. Probably this happened because multiple shard became alive in mainnet. I found out that error appears in [this](https://github.com/xssnick/tonutils-go/blob/master/ton/block.go#L489) switch case with zero value in **ab** variable. Could you please research it and maybe adding another case to this switch case would fix the problem? And then I switched mode to ProofCheckPolicyUnsafe, checks was skipped  and everything works well. Is it safe to use ProofCheckPolicyUnsafe?

**Comment by xssnick** [comment]
Hi, fixed in v1.8.8. 

About `ProofCheckPolicyUnsafe`, it is pretty safe, if you trust liteservers (for example, using public ton liteservers or your own). Most of the other libraries has no proof checks :)

**Comment by KudinovKV** [comment]
Got it. Thanks for quick reply!
