### ISSUE TITLE
Bug when calling `tlb.Message`  `ToCell(message)`

### ISSUE THREAD

**Issue by fenghaojiang** [xssnick/tonutils-go#160]
Here is my code: 
```go
func mapMessage(tx *tlb.Transaction, message tlb.Message) (*model.MessageValue, error) {
	var (
		msg = new(model.MessageValue)
		err error
	)


        // panic happened here. 
	msgCell, err := tlb.ToCell(message)
	if err != nil {
		log.Error("failed to convert message to cell", zap.String("hash", string(tx.Hash)), zap.Error(err))
		return nil, err
	}

	msg.Hash = msgCell.Hash()
}
```

```shell
panic: corrupted allowed list tag, should be [a,b,c], got .

goroutine 113 [running]:
github.com/xssnick/tonutils-go/tlb.ToCell({0x1011f6d60, 0x14000503240})
	/Users/haojiangfeng/codes/xxx/ton-etl/vendor/github.com/xssnick/tonutils-go/tlb/loader.go:481 +0x346c
```

I found the message structure: 
```go
type Message struct {
	MsgType MsgType    `tlb:"-"`
	Msg     AnyMessage `tlb:"."`
}
```

Msg AnyMessage have tag `tlb:"."`. 

Should the code of following place front of the allowed list tag check? 
tlb/loader.go/LoadFromCell,
line 190
```go
                if len(settings) == 0 || settings[0] == "." {
			nVal, err := structLoad(typeToLoad, loader, false, skipProofBranches)
			if err != nil {
				return fmt.Errorf("failed to load struct for %s, err: %w", structField.Name, err)
			}

			setVal(nVal)
			continue
		}
```

**Comment by xssnick** [comment]
Hi, thank you for the report! You are right, it should be a list of names.

This is a known issue, that is already fixed in dev branch along with some other improvements of tlb loader, you could import it in your project:
`go get -u github.com/xssnick/tonutils-go@6864fad2dd8c98cbe5427690fd3edb9ea9fea386`

**Comment by fenghaojiang** [comment]
> Hi, thank you for the report! You are right, it should be a list of names.
> 
> This is a known issue, that is already fixed in dev branch along with some other improvements of tlb loader, you could import it in your project: `go get -u github.com/xssnick/tonutils-go@6864fad2dd8c98cbe5427690fd3edb9ea9fea386`

Thank you so much! Really appreciated the efforts you made.
