### ISSUE TITLE
parse Tact map

### ISSUE THREAD

**Issue by wd-idonan** [xssnick/tonutils-go#168]
How to parse the map in Tact using Golang when I call get method
ts script: 
async getMap(provider: ContractProvider) {
        let builder = new TupleBuilder();
        let source = (await provider.get('map', builder.build())).stack;
        let result = Dictionary.loadDirect(Dictionary.Keys.BigInt(257), Dictionary.Values.BigInt(257), source.readCellOpt());
        return result;
    }

**Comment by xssnick** [comment]
Use `LoadDict` during slice (cell) reading, you can find some examples in [tests](https://github.com/xssnick/tonutils-go/blob/master/tvm/cell/dict_test.go)

**Comment by wd-idonan** [comment]
thank you
