### ISSUE TITLE
GetBalance Error

### ISSUE THREAD

**Issue by doocop** [xssnick/tonutils-go#169]
An error occurred when I tried to parse out the address through the mnemonic phrase and obtain the address balance.

I tried using the mainnet configuration file, and errors occurred with the specified node.

`2024/01/31 22:11:19 GetBalance err: failed to get account state: lite server error, code 651: too big masterchain block seqno
exit status 1`

This is why?

**Comment by xssnick** [comment]
It can be because liteserver is not in sync with the network, you can consider it as a random error and retry (request will probably go to another server), especially when using public liteserver nodes.

**Comment by nalcheg** [comment]
I'm getting same error when using "https://ton-blockchain.github.io/global.config.json", "https://ton.org/global-config.json" client configs.
Also sometimes I get `get masterchain info error (*liteclient.ConnectionPool): adnl request timeout, node xxx.xxx.xxx.xxx:yyyy` with different nodes addresses.
This problem started about two days ago.

**Comment by xssnick** [comment]
public liteservers are under load now, because of gram mining

**Comment by iw4p** [comment]
Is there a place where I can find other liteserver addresses?

**Comment by iw4p** [comment]
Just found that in the [https://ton.org/en/dev](https://ton.org/en/dev) for golang section, they wrote 
`err := client.AddConnection(context.Background(), "135.181.140.212:13206", "K0t3+IWLOXHYMvMcrGZDPs+pn58a17LFbnXoQkKc2xw=")
`
Still I am testing it but I have not get the adnl request timeout yet
