### ISSUE TITLE
User-friendly to Raw adress conversion/comparison

### ISSUE THREAD

**Issue by kvizyx** [xssnick/tonutils-go#180]
Hi! In a nutshell, i'm building an app that detect transactions from specific addresses set by user so i need to compare user-friendly addresses (that user send to app) with raw addresses from subscription channel:
```go
senderUFAddr := "sender-user-friendly-address"

go api.SubscribeOnTransactions(context.Background(), receiverAddress, lastProcessedLT, transactions)

for tx := range transactions {
	if tx.IO.In == nil || tx.IO.In.Msg == nil {
		fmt.Println("not an in message")
		continue
	}

	internalMessage, ok := tx.IO.In.Msg.(*tlb.InternalMessage)
	if !ok {
		fmt.Println("not an internal message")
		continue
	}

	senderRawAddr := internalMessage.SrcAddr.String()

	lastProcessedLT = tx.LT
}
```
How can i do this comparison with tonutils or i have to implement it on my own?

**Comment by xssnick** [comment]
Hi, to make raw address you could do this way:
```golang
raw := fmt.Sprintf("%d:%x", internalMessage.SrcAddr.Workchain(), internalMessage.SrcAddr.Data())
```

**Comment by xssnick** [comment]
```
internalMessage.SrcAddr.String()
```
returns user friendly address

**Comment by kvizyx** [comment]
I think i didn't put it that way. When user want to detect transactions from some address and send it to the app (```0QAqow_s3o17yQk8h6QXVvE0yw_7IVzohVK1qcHfTCx_wVe_``` for example) then i need to compare SrcAddr of each transaction to this address to detect whether it's transaction from address that user gave to us or not. But when i get the address from the transaction it's a bit different from one that user sent (```EQAqow_s3o17yQk8h6QXVvE0yw_7IVzohVK1qcHfTCx_wbHw``` for the address shown in the example above) so it's a problem for me how to compare them. If anything, I'm new to TON, so I apologize in advance if this is a stupid question :)

**Comment by xssnick** [comment]
This is because address flags, your address which starts from 0 is address with testnet and nonboubce flags, you could set flag to src address too using SetTestnetOnly(true) and SetBounce(false), then call String(), then they should be the same.

**Comment by kvizyx** [comment]
Thanks!
