### ISSUE TITLE
invalid seed check

### ISSUE THREAD

**Issue by wgx731** [xssnick/tonutils-go#184]
Hi @xssnick ,

I am wondering about the following [line](https://github.com/xssnick/tonutils-go/blob/master/ton/wallet/seed.go#L89)

what are we checking here? 

The official [tutorial](https://docs.ton.org/develop/smart-contracts/tutorials/wallet) [code](https://github.com/aSpite/wallet-tutorial/blob/main/Golang/Chapter%203/Deploying%20our%20wallet.go#L29) just creates the key directly.

Thanks.

**Comment by xssnick** [comment]
Hi, we are checking seed type, we doing additional hash to detect is seed with password (1) or not (0), this is how it is implemented in official ton node, see https://github.com/ton-blockchain/ton/blob/4cfe1d1a96acf956e28e2bbc696a143489e23631/tonlib/tonlib/keys/Mnemonic.cpp#L77

**Comment by xssnick** [comment]
Please use `wallet.NewSeed()`, it is simpler and better :)

**Comment by wgx731** [comment]
Thanks a lot for the quick answer, a related question about the wallet:
[README](https://github.com/xssnick/tonutils-go/blob/master/README.md#wallet) states `This library will deploy and initialize wallet contract if it is not initialized yet.`

But I am getting `SendWaitTransaction err: failed to send message: lite server error, code 0: cannot apply external message to current state : External message was not accepted` error, following basic usage example, as the wallet is inactive, any code reference to init the wallet?

Thank you very much.

**Comment by xssnick** [comment]
Probably this is because balance is 0 or not enough

**Comment by wgx731** [comment]
> Probably this is because balance is 0 or not enough

The issue is I have sent to the bounceable addresses of the wallet which I want to init previously. Thanks again for the help.
Closing the issue now.
