### ISSUE TITLE
how to parse jetton transaction to get jetton token amount and comment?

### ISSUE THREAD

**Issue by gilfoyle2021asc** [xssnick/tonutils-go#186]
when transfer jetton, i noticed the jetton amount and comment has been included in transferPayload then included into message body, my purpose is to parse tx from ListTransactions, this sdk is not supported to get jetton amount and comment, so i try to parse message body to find out ,i can get the message body by 'body:=tx.IO.In.AsInternal().Body', but how to parse the body to readable text?

**Comment by gilfoyle2021asc** [comment]
thank you very much for your replay, but the m.Amount is amount for TON , i want amount jetton token amount, which is included here : tonutils-go@v1.9.2/ton/jetton/wallet.go:87 and comment in here : github.com/xssnick/tonutils-go@v1.9.2/ton/jetton/wallet.go:92

**Comment by gilfoyle2021asc** [comment]
i am transfer jetton token like this:example/jetton-transfer/main.go:62

**Comment by gilfoyle2021asc** [comment]
which language you are using? how do you get jetton amount and comment from transaction in your language lib?

**Comment by gilfoyle2021asc** [comment]
thanks help, problem solved ,there is a decode func existing in source code

**Comment by estw272** [comment]
@gilfoyle2021asc hi, can you share how you solved it?
