### ISSUE TITLE
how can i get one transcation info by hash?

### ISSUE THREAD

**Issue by zy166317** [xssnick/tonutils-go#187]

**Comment by xssnick** [comment]
You can't, need an index for this. But you can get transaction by address + lt, [using this methid](https://github.com/xssnick/tonutils-go/blob/master/ton/transactions.go#L103)

**Comment by zy166317** [comment]
> You can't, need an index for this. But you can get transaction by address + lt, [using this methid](https://github.com/xssnick/tonutils-go/blob/master/ton/transactions.go#L103)
please give one demo for getTranscation func,i only want get one record

**Comment by zy166317** [comment]
@xssnick i only want use GetTransaction method get one transcation by address+lt,please give me use this method demo.thank you

**Comment by Wbqqqq** [comment]
so, if I only have transcation hash, how can I find it? the sdk don't support, right? but https://tonscan.org/blocks can search
