### ISSUE TITLE
 i only want use GetTransaction method get one transcation by address+lt,please give me use this method demo.thank you

### ISSUE THREAD

**Issue by zy166317** [xssnick/tonutils-go#188]

**Comment by zy166317** [comment]
![image](https://github.com/xssnick/tonutils-go/assets/54349377/a51d0ce9-8e69-4732-9ec8-44961e86b784)

**Comment by xssnick** [comment]
Ah, block should be a shard block where this transaction has happened. Maybe it will be simpler for you to call `ListTransactions` on account and find it

**Comment by zy166317** [comment]
> Ah, block should be a shard block where this transaction has happened. Maybe it will be simpler for you to call `ListTransactions` on account and find it

@xssnick iwant to know transaction struct params description

**Comment by xssnick** [comment]
https://docs.ton.org/develop/data-formats/transaction-layout

**Comment by zy166317** [comment]
> https://docs.ton.org/develop/data-formats/transaction-layout

thanks
