### ISSUE TITLE
如何设置excess地址

### ISSUE THREAD

**Issue by arvin-lau** [xssnick/tonutils-go#204]
`		token := jetton.NewJettonMasterClient(api, address.MustParseAddr(contractAddrStr))

		// find our jetton wallet
		tokenWallet, err := token.GetJettonWallet(context.Background(), wallet.WalletAddress())
		if err != nil {
			return nil, err
		}
		comment, err := pkgTonWallet.CreateCommentCell(memo)
		if err != nil {
			return nil, err
		}
		transferPayload, err := tokenWallet.BuildTransferPayloadV2(address.MustParseAddr(toStr), address.MustParseAddr(responseToStr), tlb.MustFromNano(value, tokenDecimal), tlb.MustFromTON("0.000000001"), comment, nil)
		if err != nil {
			return nil, err
		}
		unsignedTx = pkgTonWallet.SimpleMessage(tokenWallet.Address(), tlb.MustFromTON("0.05"), transferPayload)
`

构建交易,发现excess地址永远是jetton收款地址(to),如何将excess设置成发送方地址(from)?

**Comment by arvin-lau** [comment]
1. response address一旦设置成了from,那么notify也会跟着变成from地址,而excess地址依旧是收款地址(https://tonviewer.com/transaction/5a820fa0634b5e09fb39fb1dd93b983c7046f8d1b06f06f1f8081d213d850275)
2. response address地址设置成收款地址,那么notify和excess都会是收款地址 (https://tonviewer.com/transaction/6a9d454846865d3c4862096f10cf05f3935a01eec6df294d5d070bd28442707a)
3.  总结: 更改不了excess地址,他只能是收款地址,这是代码本身的设定还是我使用时出了问题?

**Comment by xssnick** [comment]
Hi, this is how jetton wallet contract works, there are only 2 addresses can be passed to contract, exess goes to response address

**Comment by arvin-lau** [comment]
Thanks for you reply. I've found the cause of the problem, it's a problem with my usage, tonutils-go is fine.

**Comment by LindenWang01** [comment]
> Thanks for you reply. I've found the cause of the problem, it's a problem with my usage, tonutils-go is fine.

请问下notify是怎么出来的，我看了一圈也没找到notify设置的地方，浏览器里也不显示我发起交易的notify？
https://testnet.tonviewer.com/transaction/5887fdda806a8285b7cade406246a4ec789e60519aca1b5257612f509d4c4ad7
