### ISSUE TITLE
Just want build a boc

### ISSUE THREAD

**Issue by Wbqqqq** [xssnick/tonutils-go#211]
I use this code. and want to build a boc .

            `transfer, err := w.BuildTransfer(addr, tlb.MustFromTON("0.003"), bounce, "Hello from tonutils-go!")
                if err != nil {
	                log.Fatalln("Transfer err:", err.Error())
	                return
                }
                
                ext, err := w.BuildExternalMessageForMany(context.Background(), []*wallet.Message{transfer})
                
                req, err := tlb.ToCell(ext)
                
                println(base64.URLEncoding.EncodeToString(req.ToBOCWithFlags(false)))`

then I want to use api to send my message, 
![image](https://github.com/xssnick/tonutils-go/assets/17332298/9eaa558a-8ec1-4185-8373-bd78efa30b5b)

always incorrectly. 

Can you help me, dear friend😂

**Comment by xssnick** [comment]
Hi, try `base64.StdEncoding`

**Comment by Wbqqqq** [comment]
omg! Finally correct! thank you sir! I love you!  🌹
