### ISSUE TITLE
api.SubscribeOnTransactions cannot monitor transactions with ton transfer 0

### ISSUE THREAD

**Issue by daewoochen** [xssnick/tonutils-go#214]
Hi, 
1. I sent a ton transfer transaction
`bounce := false`
`transfer, _ := w.BuildTransfer(to, tlb.MustFromTON("0"), bounce, "test")`
`tx, _, _ := w.SendWaitTransaction(ctx, transfer)`
2. When monitoring the to address to use the following code, I cannot receive tx, but I can see the transaction in explorer
`go api.SubscribeOnTransactions(context.Background(), treasuryAddress, lastProcessedLT, transactions)`
`for tx := range transactions {}`
3. But when I modify the sent ton amount to not be 0, I can monitor the transaction, so how should I modify code to monitor the transaction with ton transfer of 0? 
Thank you!

**Comment by xssnick** [comment]
Hi, could you please share transaction (explorer url)?

**Comment by daewoochen** [comment]
> Hi, could you please share transaction (explorer url)?

this: https://testnet.tonviewer.com/transaction/256b0f3b23fdd69dc6ef78b0cee4b65dfe6c8fb8b4427601cc7ea102dcb6bdd9

**Comment by daewoochen** [comment]
> Hi, could you please share transaction (explorer url)?

transfer 0 ton: https://testnet.tonviewer.com/transaction/0193b117167bd24647b0b898da8bab43690f5e09b72a1c389202142bfe4790af

**Comment by xssnick** [comment]
It looks like you using `tx.String()`, it prints nothing if amount is 0, but transaction exists itself and you can use it, just print something like tx.LT or whatever you need :)

I will fix this print of tx data in the next version.

**Comment by daewoochen** [comment]
Yes, I used tx.String() to print the message, this problem has been solved, thanks!
