### ISSUE TITLE
How to exclude jetton from monitoring transactions and only accept ton transactions

### ISSUE THREAD

**Issue by SpadesA99** [xssnick/tonutils-go#237]
[https://github.com/xssnick/tonutils-go/blob/master/example/accept-payments/main.go#L70](https://github.com/xssnick/tonutils-go/blob/master/example/accept-payments/main.go#L70)

**Comment by xssnick** [comment]
Hi, just ignore jetton amounts, remove this block https://github.com/xssnick/tonutils-go/blob/9db1a1391b6c8007f5d2e6ee812aeb55764c50c8/example/accept-payments/main.go#L77

**Comment by xssnick** [comment]
Every transaction carries some amount of ton, you can consider only it
