### ISSUE TITLE
How to get transactions by accountBlock?

### ISSUE THREAD

**Issue by fishTsai20** [xssnick/tonutils-go#239]
By your example. 
slcTx := txKV.Value
var rawTx tlb.Transaction
					if err = tlb.LoadFromCell(&rawTx, slcTx.MustLoadRef()); err != nil {
						return fmt.Errorf("faled to parse transaction: %w", err)
					}
But as ton's doc said, transaction's type is as below:
acc_trans#5 account_addr:bits256
            transactions:(HashmapAug 64 ^Transaction CurrencyCollection)
            state_update:^(HASH_UPDATE Account)
          = AccountBlock;
slcTx's type isn't CurrencyCollection??
why CurrencyCollection has a ref?
why the code as below not work?
err := tlb.LoadFromCell(&txb, txKV.Key.MustLoadRef())

Do you have any doc that explain how to load cell?

**Comment by xssnick** [comment]
`HashmapAug` is compatible with Hashmap for parsing, augmented element concatenated with value, so first you should parse CurrencyCollection from slice and then load tlb.Transaction, then should work

**Comment by fishTsai20** [comment]
got it!
