### ISSUE TITLE
How do I deploy an NFT collection?

### ISSUE THREAD

**Issue by kekodmc** [xssnick/tonutils-go#240]
Tell me about it,please

**Comment by kekodmc** [comment]
W5 wallet by the way

**Comment by xssnick** [comment]
Hi, see example https://github.com/xssnick/tonutils-go/blob/master/example/deploy-nft-collection/main.go

**Comment by kekodmc** [comment]
> Hi, see example https://github.com/xssnick/tonutils-go/blob/master/example/deploy-nft-collection/main.go

You are right,think you
