### ISSUE TITLE
MustFromTON / SendWaitTransaction Amount discrepancy

### ISSUE THREAD

**Issue by pddmergilla-ns** [xssnick/tonutils-go#249]
```
tx, block, err := w.SendWaitTransaction(context.Background(), &wallet.Message{
    Mode: wallet.PayGasSeparately // pay fees separately (from balance, not from amount)
    InternalMessage: &tlb.InternalMessage{
        Bounce:  true, // return amount in case of processing error
        DstAddr: address.MustParseAddr(dstAddress),
        Amount:  tlb.MustFromTON("0.06"),
        Body:    payload,
        },
})
```

hi, whenever I use this transaction, instead of sending exact "0.06" TONs, I'm getting some other additional amount.

![image](https://github.com/user-attachments/assets/97b585b3-1ca9-4088-a65d-abcce23ebe2d)

I tried Removing `wallet.PayGasSeparately` (which gave me reduced amount) or even tried `wallet.PayGasSeparately + wallet.IgnoreErrors` but still same transaction result..
I also tried MustFromNano but with same result..

is there a way I can transfer the exact "0.06" amount?

Thanks for the library!

**Comment by laalauren1** [comment]
> ```
> tx, block, err := w.SendWaitTransaction(context.Background(), &wallet.Message{
>     Mode: wallet.PayGasSeparately // pay fees separately (from balance, not from amount)
>     InternalMessage: &tlb.InternalMessage{
>         Bounce:  true, // return amount in case of processing error
>         DstAddr: address.MustParseAddr(dstAddress),
>         Amount:  tlb.MustFromTON("0.06"),
>         Body:    payload,
>         },
> })
> ```
> 
> hi, whenever I use this transaction, instead of sending exact "0.06" TONs, I'm getting some other additional amount.
> 
> ![image](https://private-user-images.githubusercontent.com/179579815/365984926-97b585b3-1ca9-4088-a65d-abcce23ebe2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjcxOTIsIm5iZiI6MTcyNTk2Njg5MiwicGF0aCI6Ii8xNzk1Nzk4MTUvMzY1OTg0OTI2LTk3YjU4NWIzLTFjYTktNDA4OC1hNjVkLWFiY2NlMjNlYmUyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMTE0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODI2M2ZkY2MwNmU0OTMyYjgzZTZkMmVmMzA5NGU3NTMwMDhmNTFhYTBiNDE2MDk1YTYyYTNlY2FiNGRkNWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7ArVCEQ2eJmPJHECsheCwhBoYG3FySitPGotmafczBM)
> 
> I tried Removing `wallet.PayGasSeparately` (which gave me reduced amount) or even tried `wallet.PayGasSeparately + wallet.IgnoreErrors` but still same transaction result.. I also tried MustFromNano but with same result..
> 
> is there a way I can transfer the exact "0.06" amount?
> 
> Thanks for the library!

@pddmergilla-ns  it seems like you're experiencing some unexpected additional amounts when you make transactions with "0.06" TONs It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Ton Network DApps Support Ticket Requests](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by xssnick** [comment]
Hi, share your transaction please (link to explorer)

**Comment by xssnick** [comment]
In transaction tree[i see exact 0.06 ](https://testnet.tonviewer.com/transaction/2e478fb83e4ff45b1a5b2af1ba52d3f4a7cc854ccfd493c8eae7dc613ab5984d?section=trace), looks like explorer just displaying some fees or something

**Comment by pddmergilla-ns** [comment]
![image](https://github.com/user-attachments/assets/4934dab6-bfc3-408b-81f0-3f4a56e1de87)

Ah, yes I can see that when you hover on the value it says the exact amount.
So it doesn't have any issue with this? My only concern is I'm also getting a `⬆️ Sent TON` after the `Contract Called` so maybe I'm paying gas more than I should?
But if not then I think maybe it's fine

**Comment by pddmergilla-ns** [comment]
YEEEEEEESSSSS
This works flawlessly man, thanks! <3
