### ISSUE TITLE
Properly get the V5R1 wallet

### ISSUE THREAD

**Issue by pddmergilla-ns** [xssnick/tonutils-go#250]
hi, please help me with this..

I need to get my V5R1 wallet so I'm using this:

```
w, err := wallet.FromSeed(api, words, wallet.ConfigV5R1Final{
	NetworkGlobalID: wallet.MainnetGlobalID,
})
```

and true enough I'm getting my wallet, checked the balance and it's correct.
However I can't use this in a transaction, my guess is that because I'm using Mainnet as the GlobalID and we're using testnet for testing.
I'm getting this kind of error:

![image](https://github.com/user-attachments/assets/35ac4f75-46d9-4677-a063-0f8ca1f2e0de)

But whenever I tried 
```
w, err := wallet.FromSeed(api, words, wallet.ConfigV5R1Final{
	NetworkGlobalID: wallet.TestnetGlobalID,
})
```

I'm getting a different wallet address (which is unused, and the balance is zero) so I can't use that as well.

Is there a way to get a V5R1 wallet for testing?

Thanks!

**Comment by laalauren1** [comment]
> hi, please help me with this..
> 
> I need to get my V5R1 wallet so I'm using this:
> 
> ```
> w, err := wallet.FromSeed(api, words, wallet.ConfigV5R1Final{
> 	NetworkGlobalID: wallet.MainnetGlobalID,
> })
> ```
> 
> and true enough I'm getting my wallet, checked the balance and it's correct. However I can't use this in a transaction, my guess is that because I'm using Mainnet as the GlobalID and we're using testnet for testing. I'm getting this kind of error:

@pddmergilla-ns It seems like you are encountering an issue with using your V5R1 wallet for transactions due to the Mainnet GlobalID while testing on the testnet.It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID VR07638
Please see the link below to our dedicated support line:
[V5R1 wallet Network DApps Support Ticket Requests](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by xssnick** [comment]
Hi, share your ton address (which is with balance), please, or check transaction exit code

**Comment by xssnick** [comment]
I see that exit code is [137 (external_send_message_must_have_ignore_errors_send_mode)](https://github.com/ton-blockchain/wallet-contract-v5/blob/main/contracts/wallet_v5.fc#L10C18-L10C73), for v5 message mode must include `IgnoreErrors` flag, eg: `Mode: PayGasSeparately + IgnoreErrors`

**Comment by pddmergilla-ns** [comment]
> I see that exit code is [137 (external_send_message_must_have_ignore_errors_send_mode)](https://github.com/ton-blockchain/wallet-contract-v5/blob/main/contracts/wallet_v5.fc#L10C18-L10C73), for v5 message mode must include `IgnoreErrors` flag, eg: `Mode: PayGasSeparately + IgnoreErrors`

this is working well, thanks! <3
