### ISSUE TITLE
How can i get processed transactions for highload wallet?

### ISSUE THREAD

**Issue by n1ks2n** [xssnick/tonutils-go#258]
Hi guys, want to monitor highload wallet transactions for actual operations statuses. And to do this highload wallet contract has method `getProcessed` that requires queryID, but in current SDK queryID is randomized inside the SDK and it is not returned anywhere in method like `SendManyWaitTransaction` or `SendManyWaitTxHash`. The only idea i have right now is to fork the SDK and update highload wallet interface/methods to add query id in  initial`messages []*Message` as they are passed by link after sent. Or maybe i miss something and there is a way to get queryID for sent messages?

**Comment by xssnick** [comment]
Hi, for HW3 you can set your own query id by default ([example](https://github.com/xssnick/tonutils-go/blob/master/example/highload-wallet/main.go#L35))

If you are using HW2 you can also hook query id creation, like this:
```go
w.GetSpec().(*wallet.SpecHighloadV2R2).SetCustomQueryIDFetcherWithContext(func(ctx context.Context, subWalletId uint32) (ttl uint32, randPart uint32, err error) {
		return ...
})
```
