### ISSUE TITLE
different addresses v5 in tonkeeper and in the library

### ISSUE THREAD

**Issue by iArt4ik** [xssnick/tonutils-go#278]
here is the wallet seed phrase (created in thinkeeper)
garden usual warm room bacon onion sing surprise public banner afford elevator dirt genuine position industry elite apology candy happy much saddle soap cruel

I'm installing version 5
here is the address that thinkeeper gives: UQAhRouG9NO82A6Jhkd80_jkyUBNngiOkrQW5gMAinOuIZZz

here is the library v5 final:
bounce: true EQApCfrgC4s2QRm5q4jElfzL2j1b0jx2i7Lj-spJzZmeRlF4
bounce: false UQApCfrgC4s2QRm5q4jElfzL2j1b0jx2i7Lj-spJzZmeRgy9
raw bounce true: 0:2909fae00b8b364119b9ab88c495fccbda3d5bd23c768bb2e3faca49cd999e46
raw bounce false: 0:2909fae00b8b364119b9ab88c495fccbda3d5bd23c768bb2e3faca49cd999e46

here is the library v5 beta:
bounce: true EQDqWuMFNTRPWwOsamgL-9NvSVN8rAwu3i2HR3W7NMI1feDs
bounce: false UQDqWuMFNTRPWwOsamgL-9NvSVN8rAwu3i2HR3W7NMI1fb0p
raw bounce true: 0:ea5ae30535344f5b03ac6a680bfbd36f49537cac0c2ede2d874775bb34c2357d
raw bounce  false: 0:ea5ae30535344f5b03ac6a680bfbd36f49537cac0c2ede2d874775bb34c2357d

here is the code 

```
wall, err := wallet.FromSeed(object.tonClientService().Api(), request.Seed, request.Type)
if err != nil {
	return nil, err
}

log.Println("bounce: true", wall.WalletAddress().Bounce(true).String())
log.Println("bounce: false", wall.WalletAddress().Bounce(false).String())
log.Println("raw bounce true:", "0:"+hex.EncodeToString(wall.WalletAddress().Bounce(true).Data()))
log.Println("raw bounce false:", "0:"+hex.EncodeToString(wall.WalletAddress().Bounce(false).Data()))
```

here is the code for getting the version

```
switch object {
case VersionV4R2:
	return wallet.V4R2, nil
case VersionV5R1Beta:
	return wallet.ConfigV5R1Beta{NetworkGlobalID: wallet.MainnetGlobalID}, nil
case VersionV5R1Final:
	return wallet.ConfigV5R1Final{NetworkGlobalID: wallet.MainnetGlobalID}, nil
default:
	return nil, fmt.Errorf("unsupported wallet version: %s", object)
}
```

i.e. it is clear that I am creating the required version and in the network main

why may the addresses not match? does anyone have any ideas?

-----------------

вот сид фраза кошелька (создан в тонкипер)
garden usual warm room bacon onion sing surprise public banner afford elevator dirt genuine position industry elite apology candy happy much saddle soap cruel

ставлю версию 5
вот адрес который выдает тонкипер: UQAhRouG9NO82A6Jhkd80_jkyUBNngiOkrQW5gMAinOuIZZz

вот библиотека v5 final:
bounce: true EQApCfrgC4s2QRm5q4jElfzL2j1b0jx2i7Lj-spJzZmeRlF4
bounce: false UQApCfrgC4s2QRm5q4jElfzL2j1b0jx2i7Lj-spJzZmeRgy9
raw bounce true: 0:2909fae00b8b364119b9ab88c495fccbda3d5bd23c768bb2e3faca49cd999e46
raw bounce false: 0:2909fae00b8b364119b9ab88c495fccbda3d5bd23c768bb2e3faca49cd999e46

вот библиотека v5 beta:
bounce: true EQDqWuMFNTRPWwOsamgL-9NvSVN8rAwu3i2HR3W7NMI1feDs
bounce: false UQDqWuMFNTRPWwOsamgL-9NvSVN8rAwu3i2HR3W7NMI1fb0p
raw bounce true: 0:ea5ae30535344f5b03ac6a680bfbd36f49537cac0c2ede2d874775bb34c2357d
raw bounce  false: 0:ea5ae30535344f5b03ac6a680bfbd36f49537cac0c2ede2d874775bb34c2357d

вот код

```
wall, err := wallet.FromSeed(object.tonClientService().Api(), request.Seed, request.Type)
if err != nil {
	return nil, err
}

log.Println("bounce: true", wall.WalletAddress().Bounce(true).String())
log.Println("bounce: false", wall.WalletAddress().Bounce(false).String())
log.Println("raw bounce true:", "0:"+hex.EncodeToString(wall.WalletAddress().Bounce(true).Data()))
log.Println("raw bounce false:", "0:"+hex.EncodeToString(wall.WalletAddress().Bounce(false).Data()))
```

код получения версии вот
```
switch object {
case VersionV4R2:
	return wallet.V4R2, nil
case VersionV5R1Beta:
	return wallet.ConfigV5R1Beta{NetworkGlobalID: wallet.MainnetGlobalID}, nil
case VersionV5R1Final:
	return wallet.ConfigV5R1Final{NetworkGlobalID: wallet.MainnetGlobalID}, nil
default:
	return nil, fmt.Errorf("unsupported wallet version: %s", object)
}
```

т.е. видно что я создаю нужную версию и в сети main

почему адреса могут не совпадать? есть у кого идеи?

**Comment by xssnick** [comment]
Tried to generate seed in keeper and compare address (and vice-versa), it was same, looks like you comparing wrong seed or something

**Comment by iArt4ik** [comment]
> Tried to generate seed in keeper and compare address (and vice-versa), it was same, looks like you comparing wrong seed or something

here is a clean example

```
package main

import (
  "context"
  "encoding/hex"
  "github.com/xssnick/tonutils-go/liteclient"
  "github.com/xssnick/tonutils-go/ton"
  "github.com/xssnick/tonutils-go/ton/wallet"
  "log"
  "strings"
)

func main() {
  client := liteclient.NewConnectionPool()

  cfg, err := liteclient.GetConfigFromUrl(context.Background(), "https://ton.org/global.config.json")
  if err != nil {
    log.Fatalln("get config err: ", err.Error())
    return
  }

  err = client.AddConnectionsFromConfig(context.Background(), cfg)
  if err != nil {
    log.Fatalln("connection err: ", err.Error())
    return
  }

  api := ton.NewAPIClient(client, ton.ProofCheckPolicyFast).WithRetry()
  api.SetTrustedBlockFromConfig(cfg)

  words := strings.Split("garden usual warm room bacon onion sing surprise public banner afford elevator dirt genuine position industry elite apology candy happy much saddle soap cruel", " ")

  wall, err := wallet.FromSeed(api, words, wallet.ConfigV5R1Beta{NetworkGlobalID: wallet.MainnetGlobalID})
  if err != nil {
    log.Fatalln("could not create wallet: %v", err)
    return
  }

  log.Println("bounce: true", wall.WalletAddress().Bounce(true).String())
  log.Println("bounce: false", wall.WalletAddress().Bounce(false).String())
  log.Println("raw bounce true:", "0:"+hex.EncodeToString(wall.WalletAddress().Bounce(true).Data()))
  log.Println("raw bounce false:", "0:"+hex.EncodeToString(wall.WalletAddress().Bounce(false).Data()))
}
```

I also imported this seed phrase into thinkeeper, the address for version 5 was UQAhRouG9NO82A6Jhkd80_jkyUBNngiOkrQW5gMAinOuIZZz

Please check again with this seed phrase, maybe I'm doing something wrong, but I can't figure out what)) I really hope for help

here is the log for the v5 beta config:
2024/11/14 11:57:49 bounce: true EQBjoZyClIQfGVw2kgtEr0T8TK2DZ6h2bxwyK0WwSI-gTF7O
2024/11/14 11:57:49 bounce: false UQBjoZyClIQfGVw2kgtEr0T8TK2DZ6h2bxwyK0WwSI-gTAML
2024/11/14 11:57:49 raw bounce true: 0:63a19c8294841f195c36920b44af44fc4cad8367a8766f1c322b45b0488fa04c
2024/11/14 11:57:49 raw bounce false: 0:63a19c8294841f195c36920b44af44fc4cad8367a8766f1c322b45b0488fa04c

here is the log for the v5 final config:
2024/11/14 11:54:09 bounce: true EQAr8ULqJhlSilCgITHqetusuD6kQcG2wnj7VTMc1A3owu02
2024/11/14 11:54:09 bounce: false UQAr8ULqJhlSilCgITHqetusuD6kQcG2wnj7VTMc1A3owrDz
2024/11/14 11:54:09 raw bounce true: 0:2bf142ea2619528a50a02131ea7adbacb83ea441c1b6c278fb55331cd40de8c2
2024/11/14 11:54:09 raw bounce false: 0:2bf142ea2619528a50a02131ea7adbacb83ea441c1b6c278fb55331cd40de8c2

-----

вот чистый пример

```
package main

import (
  "context"
  "encoding/hex"
  "github.com/xssnick/tonutils-go/liteclient"
  "github.com/xssnick/tonutils-go/ton"
  "github.com/xssnick/tonutils-go/ton/wallet"
  "log"
  "strings"
)

func main() {
  client := liteclient.NewConnectionPool()

  cfg, err := liteclient.GetConfigFromUrl(context.Background(), "https://ton.org/global.config.json")
  if err != nil {
    log.Fatalln("get config err: ", err.Error())
    return
  }

  err = client.AddConnectionsFromConfig(context.Background(), cfg)
  if err != nil {
    log.Fatalln("connection err: ", err.Error())
    return
  }

  api := ton.NewAPIClient(client, ton.ProofCheckPolicyFast).WithRetry()
  api.SetTrustedBlockFromConfig(cfg)

  words := strings.Split("garden usual warm room bacon onion sing surprise public banner afford elevator dirt genuine position industry elite apology candy happy much saddle soap cruel", " ")

  wall, err := wallet.FromSeed(api, words, wallet.ConfigV5R1Beta{NetworkGlobalID: wallet.MainnetGlobalID})
  if err != nil {
    log.Fatalln("could not create wallet: %v", err)
    return
  }

  log.Println("bounce: true", wall.WalletAddress().Bounce(true).String())
  log.Println("bounce: false", wall.WalletAddress().Bounce(false).String())
  log.Println("raw bounce true:", "0:"+hex.EncodeToString(wall.WalletAddress().Bounce(true).Data()))
  log.Println("raw bounce false:", "0:"+hex.EncodeToString(wall.WalletAddress().Bounce(false).Data()))
}
```

я так же эту сид фразу импортировал в тонкипер, адрес для версии 5 получился UQAhRouG9NO82A6Jhkd80_jkyUBNngiOkrQW5gMAinOuIZZz

проверь еще раз пожалуйста с этой сид фразой, может я конечно что-то не то делаю, но я не могу понять, что )) очень надеюсь на помощь

вот лог для конфига v5 beta:
2024/11/14 11:57:49 bounce: true EQBjoZyClIQfGVw2kgtEr0T8TK2DZ6h2bxwyK0WwSI-gTF7O
2024/11/14 11:57:49 bounce: false UQBjoZyClIQfGVw2kgtEr0T8TK2DZ6h2bxwyK0WwSI-gTAML
2024/11/14 11:57:49 raw bounce true: 0:63a19c8294841f195c36920b44af44fc4cad8367a8766f1c322b45b0488fa04c
2024/11/14 11:57:49 raw bounce false: 0:63a19c8294841f195c36920b44af44fc4cad8367a8766f1c322b45b0488fa04c

вот лог для конфига v5 final:
2024/11/14 11:54:09 bounce: true EQAr8ULqJhlSilCgITHqetusuD6kQcG2wnj7VTMc1A3owu02
2024/11/14 11:54:09 bounce: false UQAr8ULqJhlSilCgITHqetusuD6kQcG2wnj7VTMc1A3owrDz
2024/11/14 11:54:09 raw bounce true: 0:2bf142ea2619528a50a02131ea7adbacb83ea441c1b6c278fb55331cd40de8c2
2024/11/14 11:54:09 raw bounce false: 0:2bf142ea2619528a50a02131ea7adbacb83ea441c1b6c278fb55331cd40de8c2
