### ISSUE TITLE
Traces for transfers

### ISSUE THREAD

**Issue by niknaylos** [xssnick/tonutils-go#283]
Hi, can you explain me how can I build traces for jetton transaction? I would appreciate any help and possibly an example
e.g how do I get tx hash of transaction to binance having only initial transaction info:

https://tonviewer.com/transaction/4728981b2d65d55aa377ba70a9a99824a4132b00cb91fd1721eb90f3c177abab?section=trace

<img width="954" alt="Screenshot 2024-11-23 at 17 04 37" src="https://github.com/user-attachments/assets/64c92e9e-30e0-4864-a1a0-a6a16d3fdb69">

**Comment by wythers** [comment]
emm, when calling `SendWaitTransaction` to send a jetton transaction,  it will back a return of the transaction info, and the transaction TX hash included in.
```Golang
	tx, _, err := w.SendWaitTransaction(ctx, msg)
	if err != nil {
		panic(err)
	}
	log.Println("transaction confirmed, hash:", base64.StdEncoding.EncodeToString(tx.Hash))

```
More detailed examples are in `example` dir.   

And the `SendWaitTransaction` does two things. First, it gets the account state before sending, with the focus on LT, and sends the jetton payload to your wallet block. Second, it monitors your wallet block from the LT. Once an external message arrives and the hash value of the payload is equal to the hash value of the payload you sent and something, it will return the information of this transaction.
